---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-fabric
  namespace: argocd
  labels:
    build: dev
spec:
  project: product-generation
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: applications/data-fabric/overlays/dev
    repoURL: 'https://github.com/Bravesguy18/flux.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
