---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg-cluster
  namespace: argocd
  labels:
    build: idle
spec:
  project: product-generation
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: clusters/idle
    repoURL: 'https://github.com/Bravesguy18/flux.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
